name: dbt_etl_test
version: '1.0'
config-version: 2

profile: dbt_etl_test # Nome do perfil do dbt

# Está é a configuração do perfil do dbt.
# Define o nome do perfil e a versão do dbt.
# O perfil contém as informações de conexão com o banco de dados.

model-paths: ["models"] # Caminho para os modelos do dbt
target-path: "target" # Caminho para os arquivos gerados pelo dbt
clean-targets: ["target", "dbt_packages"] # Caminhos para limpar os arquivos gerados pelo dbt

models:
  dbt_etl_test:
    # +schema: public # Define o esquema padrão para os modelos
    #+materialized: view # Define o tipo de materialização padrão para os modelos

    raw:
      +materialized: table
    bronze:
      +materialized: table
    silver:
      +materialized: table
    gold:
      +materialized: view
