version: 2

sources:
  - name: public
    description: "Fonte de dados bruta"
    schema: public
    tables:
      - name: regioes
        description: "Tabela de regiões"
      - name: clientes
        description: "Tabela de clientes"
      - name: fornecedores
        description: "Tabela de fornecedores"
      - name: produtos
        description: "Tabela de produtos"
      - name: vendas
        description: "Tabela de vendas"

models:
  # Raw camada
  - name: regioes
    description: "Raw camada - regiões"
    # columns:
    #   - name: regiao_id
    #     tests: [not_null, unique]
    #   - name: nome
    #     tests: [not_null]
  - name: clientes
    description: "Raw camada - clientes"  
    columns:
      - name: cliente_id
        tests: [not_null, unique]
      - name: email
        tests: [not_null]
  - name: fornecedores
    description: "Raw camada - fornecedores"    
    columns:
      - name: fornecedor_id
        tests: [not_null, unique]
  - name: produtos
    description: "Raw camada - produtos"
    columns:
      - name: produto_id
        tests: [not_null, unique]
      - name: nome
        tests: [not_null]
  - name: vendas
    description: "Raw camada - vendas"
    columns:
      - name: venda_id
        tests: [not_null, unique]
      - name: cliente_id
        tests:
          - relationships:
              to: ref('raw_clientes')
              field: cliente_id
  
  # Silver camada
  - name: slv_produtos
    description: "Silver camada - produtos"
    # columns:
    #   - name: produto_id
    #     tests: [not_null, unique]
    #   - name: nome
    #     tests: [not_null]
  - name: slv_vendas
    description: "Silver camada - vendas"
    # columns:
    #   - name: venda_id
    #     tests: [not_null, unique]
    #   - name: cliente_id
    #     tests:
    #       - relationships:
    #           to: ref('slv_clientes')
    #           field: cliente_id
        
  # Bronze camada
  - name: brz_regioes
    description: Bronze camada - regioes
    # columns:
      # - name: regiao_id
      #   tests: [not_null, unique]
      # - name: nome
      #   tests: [not_null]
  - name: brz_clientes
    description: Bronze camada - clientes
    # columns:
    #   - name: cliente_id
    #     tests: [not_null, unique]
    #   - name: email
        # tests: [not_null]
  - name: brz_fornecedores
    description: Bronze camada - fornecedores
    # columns:
    #   - name: fornecedor_id
    #     tests: [not_null, unique]
  - name: brz_produtos
    description: Bronze camada - produtos
    # columns:
    #   - name: produto_id
    #     tests: [not_null, unique]
    #   - name: nome
    #     tests: [not_null]
  - name: brz_vendas
    description: Bronze camada - vendas
    # columns:
    #   - name: venda_id
    #     tests: [not_null, unique]
    #   - name: cliente_id
    #     tests:
    #       - relationships:
    #           to: ref('brz_clientes')
    #           field: cliente_id

    
  # Gold camada
  - name: gld_fato_vendas
    description: "Gold camada - fato de vendas"
    columns:
      - name: ano
        tests: [not_null]
      - name: uf
        tests: [not_null]
      - name: nome_produto
        tests: [not_null]
      - name: total_itens
        tests: [not_null]
      - name: receita_total
        tests: [not_null]
  